# Generated by Django 5.1 on 2026-02-22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('billing', 'Billing'), ('technical', 'Technical'), ('account', 'Account'), ('general', 'General')], max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], max_length=20)),
                ('status', models.CharField(choices=[('open', 'Open'), ('in_progress', 'In Progress'), ('resolved', 'Resolved'), ('closed', 'Closed')], default='open', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'constraints': [
                    models.CheckConstraint(condition=models.Q(('title__isnull', False)), name='ticket_title_not_null'),
                    models.CheckConstraint(condition=models.Q(('description__isnull', False)), name='ticket_description_not_null'),
                    models.CheckConstraint(condition=models.Q(('title__gt', '')), name='ticket_title_not_blank'),
                    models.CheckConstraint(condition=models.Q(('description__gt', '')), name='ticket_description_not_blank'),
                    models.CheckConstraint(condition=models.Q(('category__in', ['billing', 'technical', 'account', 'general'])), name='ticket_valid_category'),
                    models.CheckConstraint(condition=models.Q(('priority__in', ['low', 'medium', 'high', 'critical'])), name='ticket_valid_priority'),
                    models.CheckConstraint(condition=models.Q(('status__in', ['open', 'in_progress', 'resolved', 'closed'])), name='ticket_valid_status'),
                ],
            },
        ),
    ]
